"""
Official candidate score resolution.

TalentCopilot currently preserves two distinct concepts:

- CandidateAnalysisState.match_score:
  the raw fit score persisted for backward compatibility;

- ranking_score:
  the consolidated candidate ranking score generated by the official
  ranking pipeline and displayed to recruiters.

UI-facing services must use get_official_candidate_score() rather than
reading analysis.match_score directly.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any


OFFICIAL_RANKING_KEYS = (
    "official_ranking_score",
    "ranking_score",
)


def _to_number(value: Any) -> float | None:
    if value is None:
        return None

    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _mapping(value: Any) -> Mapping[str, Any]:
    if isinstance(value, Mapping):
        return value
    return {}


def get_official_candidate_score(analysis: Any) -> float:
    """
    Return the consolidated candidate score used in recruiter-facing views.

    Priority:
    1. score_breakdown.official_ranking_score
    2. score_breakdown.ranking_score
    3. analysis.metadata equivalents
    4. analysis.match_score as compatibility fallback
    """

    score_breakdown = _mapping(
        getattr(analysis, "score_breakdown", None)
    )

    for key in OFFICIAL_RANKING_KEYS:
        number = _to_number(score_breakdown.get(key))
        if number is not None:
            return number

    metadata = _mapping(
        getattr(analysis, "metadata", None)
    )

    for key in OFFICIAL_RANKING_KEYS:
        number = _to_number(metadata.get(key))
        if number is not None:
            return number

    fallback = _to_number(
        getattr(analysis, "match_score", None)
    )

    return fallback if fallback is not None else 0.0
